### ISSUE TITLE
plump element/node manipulation could be made easier if parse will return them instead of root

### ISSUE THREAD

**Issue by Inc0n** [Shinmera/plump-sexp#2]
It might be easier if `plump-sexp:parse` could directly return the create element.
Then user could prepend/append/insert the child into the wanted positions.
Instead of being just only available to just appending children to the parent, by passing it as a parameter as root in `plump-sexp:parse`

**Comment by Shinmera** [comment]
Parse returns a document. If you want an easier wrapper it's like two lines of code.
